[package]
name = "magic_guns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }

bevy = "0.14.0"
bevy_egui = "0.28.0"
bevy_rapier3d = "0.27.0"
rand = "0.8.5"
